name: Create Issue from PowerShell Output

on:
  schedule:
    - cron: '*/10 * * * *'  # Run every 5 minutes
  workflow_dispatch:
    inputs:
      trigger:
        description: 'Manually trigger the workflow'
        required: false

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run PowerShell script and save output to file
      shell: pwsh
      env:
        EMAIL: ${{ secrets.EMAIL }}
        TO: ${{ secrets.TO }}
        SMTP: ${{ secrets.SMTP }}
        EMAILPW: ${{ secrets.EMAILPW }}
      run: |
        ./run.ps1
